"""create tables message and thread

Revision ID: 50ffaeb6bb41
Revises: 54dd3ead6ba8
Create Date: 2026-09-12 12:21:23.294314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ffaeb6bb41'
down_revision: Union[str, Sequence[str], None] = '54dd3ead6ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
